// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmJHbHNb3YVOnUB57Rh2o-0l5UNfkBwtM',
    appId: '1:505728002958:web:2b3a3d4f91ef34eec1d2df',
    messagingSenderId: '505728002958',
    projectId: 'k-empire-68e8c',
    authDomain: 'k-empire-68e8c.firebaseapp.com',
  storageBucket: 'k-empire-68e8c.appspot.com',
    measurementId: 'G-P0LYNL4B6G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0ycW3LUvxL44ME1MuBbsUTiws0U8nX4s',
    appId: '1:505728002958:android:dc1b87cfd4841be7c1d2df',
    messagingSenderId: '505728002958',
    projectId: 'k-empire-68e8c',
  storageBucket: 'k-empire-68e8c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZqGvNtqy_E06sOOTCjxIu5YdfSIUtUCE',
    appId: '1:505728002958:ios:34b50d8397e29785c1d2df',
    messagingSenderId: '505728002958',
    projectId: 'k-empire-68e8c',
  storageBucket: 'k-empire-68e8c.appspot.com',
    iosBundleId: 'com.example.afroforma',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZqGvNtqy_E06sOOTCjxIu5YdfSIUtUCE',
    appId: '1:505728002958:ios:34b50d8397e29785c1d2df',
    messagingSenderId: '505728002958',
    projectId: 'k-empire-68e8c',
  storageBucket: 'k-empire-68e8c.appspot.com',
    iosBundleId: 'com.example.afroforma',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmJHbHNb3YVOnUB57Rh2o-0l5UNfkBwtM',
    appId: '1:505728002958:web:39370f5d0e9ef75cc1d2df',
    messagingSenderId: '505728002958',
    projectId: 'k-empire-68e8c',
    authDomain: 'k-empire-68e8c.firebaseapp.com',
  storageBucket: 'k-empire-68e8c.appspot.com',
    measurementId: 'G-S1ZH7B2RJ0',
  );
}
